modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/SimpleTeleportersReforged"
license="MIT"

[[mods]]
modId="simpleteleporters"
version="${file.jarVersion}"
displayName="Simple Teleporters"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simple-teleporters-reforged"
logoFile="icon.png"
authors="Mrbysco, ShyNieke, Saereth"
credits="Lemonszz and Shnupbups for the original mod"
description='''
Simple Teleporters adds a craftable teleporter block to quickly travel your world!
'''
[[dependencies.simpleteleporters]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.simpleteleporters]]
modId="neoforge"
type="required"
versionRange="[21.0.143,)"
ordering="NONE"
side="BOTH"